export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRAR_USUARIO_EXITOSO = 'REGISTRAR_USUARIO_EXITOSO';
export const REGISTRAR_USUARIO_ERROR = 'REGISTRAR_USUARIO_ERROR';
export const LOGIN_USUARIO_EXISTOSO = 'LOGIN_USUARIO_EXISTOSO';
export const LOGIN_USUARIO_ERROR = 'LOGIN_USUARIO_ERROR';

export const OBTENER_USUARIO_EXITOSO = 'OBTENER_USUARIO_EXITOSO';
export const OBTENER_USUARIO_ERROR = 'OBTENER_USUARIO_ERROR';